// export { default as xxx } from './xxx';  export { default as 내보내는 파일 이름 } from './폴더명';
export { default as Main } from './main';

export { default as Oauth } from './oauth';
export { default as Mymusic } from './mymusic';
export { default as Streaming } from './streaming';
export { default as Artist } from './streaming/artist';
export { default as ArtistInfo } from './streaming/artistinfo';
export { default as Genre } from './streaming/genre';
export { default as LatestMusic } from './streaming/latestmusic';
export { default as Top100 } from './streaming/top100';
export { default as Magazine } from './magazine';
export { default as Goods } from './goods';
export { default as GoodsDetail } from './goodsDetail';
export { default as Cart } from './cart';
export { default as Popup } from './popup';
export { default as Pay } from './pay';
export { default as Complete } from './complete';
export { default as CardDetail } from './cardDetail';
export { default as PaymentCard } from './paymentCard';
export { default as CompleteCard } from './completeCard';
export { default as MyReservation } from './myReservation';
